"""Word embedding TMAP — semantic map of English words.

Embed ~800 common English words with a sentence-transformer, build a TMAP
with cosine metric, and explore semantic neighborhoods: animals cluster near
animals, countries near countries, and the tree paths between them reveal
thematic transitions (e.g., "salmon → trout → bass → guitar").

Outputs
-------
examples/word_embeddings_tmap.html     Interactive TMAP — hover to read words
examples/word_embeddings_report.txt    Semantic analysis report

Usage
-----
    python examples/word_embeddings_tmap.py
    python examples/word_embeddings_tmap.py --serve

Requirements
------------
    pip install sentence-transformers
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import numpy as np

from tmap import TMAP
from tmap.graph.analysis import (
    boundary_edges,
    confusion_matrix_from_tree,
    subtree_purity,
)
from tmap.visualization import TmapViz

OUTPUT_DIR = Path(__file__).parent

# Vocabulary: ~800 words across 15 semantic categories

VOCABULARY: dict[str, list[str]] = {
    "animals": [
        "dog",
        "cat",
        "horse",
        "cow",
        "pig",
        "sheep",
        "goat",
        "chicken",
        "duck",
        "rabbit",
        "mouse",
        "rat",
        "hamster",
        "wolf",
        "fox",
        "bear",
        "deer",
        "moose",
        "elk",
        "lion",
        "tiger",
        "leopard",
        "cheetah",
        "elephant",
        "giraffe",
        "zebra",
        "hippo",
        "rhino",
        "gorilla",
        "monkey",
        "chimpanzee",
        "orangutan",
        "baboon",
        "lemur",
        "eagle",
        "hawk",
        "falcon",
        "owl",
        "parrot",
        "penguin",
        "flamingo",
        "pelican",
        "crow",
        "sparrow",
        "robin",
        "pigeon",
        "swan",
        "heron",
        "dolphin",
        "whale",
        "shark",
        "salmon",
        "trout",
        "tuna",
        "octopus",
        "crab",
        "lobster",
        "jellyfish",
        "starfish",
        "seahorse",
        "eel",
        "butterfly",
        "bee",
        "ant",
        "spider",
        "snake",
        "scorpion",
        "beetle",
        "dragonfly",
        "mosquito",
        "cockroach",
        "grasshopper",
        "caterpillar",
        "turtle",
        "frog",
        "crocodile",
        "lizard",
        "panther",
        "jaguar",
        "hyena",
        "buffalo",
        "camel",
        "llama",
        "alpaca",
        "donkey",
        "mule",
        "otter",
        "beaver",
        "badger",
        "raccoon",
        "skunk",
        "porcupine",
        "hedgehog",
        "squirrel",
        "chipmunk",
        "weasel",
        "ferret",
        "mink",
        "koala",
        "kangaroo",
        "platypus",
        "armadillo",
        "sloth",
    ],
    "food": [
        "bread",
        "rice",
        "pasta",
        "noodle",
        "pizza",
        "burger",
        "sandwich",
        "salad",
        "soup",
        "stew",
        "steak",
        "pork",
        "beef",
        "lamb",
        "fish",
        "shrimp",
        "sushi",
        "cheese",
        "butter",
        "milk",
        "yogurt",
        "egg",
        "bacon",
        "sausage",
        "apple",
        "banana",
        "orange",
        "grape",
        "strawberry",
        "blueberry",
        "mango",
        "pineapple",
        "watermelon",
        "peach",
        "cherry",
        "tomato",
        "potato",
        "onion",
        "garlic",
        "pepper",
        "carrot",
        "broccoli",
        "spinach",
        "corn",
        "mushroom",
        "chocolate",
        "cake",
        "cookie",
        "pie",
        "donut",
        "candy",
        "honey",
        "sugar",
        "salt",
        "cinnamon",
        "vanilla",
        "ginger",
        "mustard",
        "ketchup",
        "vinegar",
        "olive",
        "avocado",
        "coconut",
        "almond",
        "walnut",
        "peanut",
        "cashew",
        "pistachio",
        "hazelnut",
        "lemon",
        "lime",
        "grapefruit",
        "cranberry",
        "raspberry",
        "blackberry",
        "plum",
        "apricot",
        "fig",
        "pomegranate",
        "papaya",
        "guava",
        "lychee",
        "kiwi",
        "melon",
        "celery",
        "cucumber",
        "zucchini",
        "eggplant",
        "pumpkin",
        "squash",
        "radish",
        "turnip",
        "beet",
        "cabbage",
        "lettuce",
        "kale",
        "cauliflower",
        "asparagus",
        "artichoke",
        "leek",
        "parsley",
        "basil",
        "oregano",
        "thyme",
        "rosemary",
        "mint",
        "cilantro",
        "dill",
        "cumin",
        "turmeric",
        "paprika",
        "saffron",
        "nutmeg",
        "clove",
        "waffle",
        "pancake",
        "croissant",
        "bagel",
        "muffin",
        "pretzel",
        "tortilla",
        "dumpling",
        "ravioli",
        "lasagna",
        "risotto",
        "paella",
        "curry",
        "hummus",
        "guacamole",
        "tahini",
        "tofu",
        "tempeh",
    ],
    "professions": [
        "doctor",
        "nurse",
        "surgeon",
        "dentist",
        "pharmacist",
        "therapist",
        "psychiatrist",
        "pediatrician",
        "cardiologist",
        "dermatologist",
        "radiologist",
        "anesthesiologist",
        "paramedic",
        "midwife",
        "optometrist",
        "teacher",
        "professor",
        "researcher",
        "scientist",
        "engineer",
        "architect",
        "programmer",
        "designer",
        "artist",
        "musician",
        "singer",
        "actor",
        "director",
        "writer",
        "journalist",
        "editor",
        "photographer",
        "lawyer",
        "judge",
        "detective",
        "police",
        "soldier",
        "pilot",
        "astronaut",
        "farmer",
        "carpenter",
        "plumber",
        "electrician",
        "mechanic",
        "chef",
        "waiter",
        "bartender",
        "accountant",
        "banker",
        "economist",
        "politician",
        "diplomat",
        "librarian",
        "firefighter",
        "biologist",
        "chemist",
        "physicist",
        "mathematician",
        "geologist",
        "astronomer",
        "archaeologist",
        "anthropologist",
        "psychologist",
        "sociologist",
        "historian",
        "philosopher",
        "linguist",
        "translator",
        "curator",
        "sculptor",
        "painter",
        "illustrator",
        "animator",
        "choreographer",
        "dancer",
        "comedian",
        "magician",
        "acrobat",
        "veterinarian",
        "botanist",
        "zoologist",
        "ecologist",
        "geneticist",
        "neuroscientist",
        "epidemiologist",
        "pathologist",
        "toxicologist",
    ],
    "sports": [
        "football",
        "soccer",
        "basketball",
        "baseball",
        "tennis",
        "golf",
        "swimming",
        "running",
        "cycling",
        "boxing",
        "wrestling",
        "judo",
        "karate",
        "fencing",
        "archery",
        "skiing",
        "snowboarding",
        "surfing",
        "sailing",
        "rowing",
        "volleyball",
        "hockey",
        "rugby",
        "cricket",
        "badminton",
        "marathon",
        "sprint",
        "javelin",
        "gymnastics",
        "diving",
        "weightlifting",
        "climbing",
        "skateboarding",
        "rollerskating",
        "triathlon",
        "pentathlon",
        "polo",
        "lacrosse",
        "squash",
        "handball",
        "curling",
        "bobsled",
        "luge",
        "biathlon",
        "decathlon",
        "hurdles",
        "discus",
        "shotput",
        "hammerthrow",
        "highjump",
        "longjump",
        "polevault",
        "steeplechase",
        "waterpolo",
        "canoeing",
        "kayaking",
        "windsurfing",
        "kitesurfing",
        "paragliding",
        "skydiving",
        "bungee",
        "rafting",
        "snorkeling",
        "scuba",
    ],
    "music": [
        "guitar",
        "piano",
        "violin",
        "drums",
        "trumpet",
        "saxophone",
        "flute",
        "clarinet",
        "cello",
        "harp",
        "harmonica",
        "accordion",
        "banjo",
        "ukulele",
        "orchestra",
        "symphony",
        "concert",
        "opera",
        "jazz",
        "blues",
        "rock",
        "pop",
        "classical",
        "hip-hop",
        "reggae",
        "country",
        "folk",
        "melody",
        "rhythm",
        "harmony",
        "choir",
        "solo",
        "trombone",
        "oboe",
        "bassoon",
        "tuba",
        "mandolin",
        "sitar",
        "didgeridoo",
        "bagpipes",
        "xylophone",
        "marimba",
        "timpani",
        "tambourine",
        "bongo",
        "tabla",
        "synthesizer",
        "organ",
        "soprano",
        "tenor",
        "baritone",
        "alto",
        "bass",
        "sonata",
        "concerto",
        "fugue",
        "prelude",
        "overture",
        "aria",
        "ballad",
        "anthem",
        "lullaby",
        "serenade",
        "requiem",
        "funk",
        "soul",
        "gospel",
        "swing",
        "bossa nova",
        "salsa",
        "techno",
        "disco",
        "grunge",
        "punk",
        "metal",
        "ska",
    ],
    "countries": [
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Portugal",
        "England",
        "Scotland",
        "Ireland",
        "Sweden",
        "Norway",
        "Denmark",
        "Finland",
        "Poland",
        "Russia",
        "Ukraine",
        "Greece",
        "Turkey",
        "Egypt",
        "Morocco",
        "Nigeria",
        "Kenya",
        "Ethiopia",
        "China",
        "Japan",
        "Korea",
        "India",
        "Thailand",
        "Vietnam",
        "Indonesia",
        "Australia",
        "Brazil",
        "Argentina",
        "Mexico",
        "Canada",
        "Cuba",
        "Peru",
        "Colombia",
        "Chile",
        "Iran",
        "Iraq",
        "Israel",
        "Pakistan",
        "Netherlands",
        "Belgium",
        "Switzerland",
        "Austria",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Serbia",
        "Croatia",
        "Slovenia",
        "Czech Republic",
        "Slovakia",
        "Lithuania",
        "Latvia",
        "Estonia",
        "Philippines",
        "Malaysia",
        "Singapore",
        "Myanmar",
        "Cambodia",
        "Mongolia",
        "Nepal",
        "Bangladesh",
        "Sri Lanka",
        "Afghanistan",
        "Saudi Arabia",
        "Yemen",
        "Oman",
        "Qatar",
        "Kuwait",
        "Jordan",
        "Lebanon",
        "Syria",
        "Libya",
        "Tunisia",
        "Algeria",
        "Sudan",
        "Ghana",
        "Senegal",
        "Tanzania",
        "Uganda",
        "Mozambique",
        "Zimbabwe",
        "Botswana",
        "Namibia",
        "Madagascar",
        "Angola",
        "Congo",
        "Venezuela",
        "Ecuador",
        "Bolivia",
        "Paraguay",
        "Uruguay",
        "Panama",
        "Costa Rica",
        "Guatemala",
        "Honduras",
        "Jamaica",
        "Haiti",
        "Dominican Republic",
        "Trinidad",
        "New Zealand",
        "Iceland",
    ],
    "cities": [
        "Paris",
        "London",
        "Berlin",
        "Rome",
        "Madrid",
        "Barcelona",
        "Amsterdam",
        "Vienna",
        "Prague",
        "Budapest",
        "Warsaw",
        "Moscow",
        "Istanbul",
        "Athens",
        "Lisbon",
        "Dublin",
        "Edinburgh",
        "Copenhagen",
        "Stockholm",
        "Oslo",
        "Helsinki",
        "Brussels",
        "Zurich",
        "Geneva",
        "Tokyo",
        "Beijing",
        "Shanghai",
        "Seoul",
        "Bangkok",
        "Singapore",
        "Mumbai",
        "Delhi",
        "Dubai",
        "Cairo",
        "Lagos",
        "Nairobi",
        "New York",
        "Los Angeles",
        "Chicago",
        "San Francisco",
        "Miami",
        "Toronto",
        "Vancouver",
        "Montreal",
        "Mexico City",
        "Havana",
        "Buenos Aires",
        "Rio de Janeiro",
        "Lima",
        "Bogota",
        "Santiago",
        "Sydney",
        "Melbourne",
        "Auckland",
        "Johannesburg",
        "Cape Town",
    ],
    "colors": [
        "red",
        "blue",
        "green",
        "yellow",
        "orange",
        "purple",
        "pink",
        "brown",
        "black",
        "white",
        "gray",
        "silver",
        "gold",
        "crimson",
        "scarlet",
        "turquoise",
        "cyan",
        "magenta",
        "violet",
        "indigo",
        "maroon",
        "beige",
        "ivory",
        "coral",
        "amber",
        "teal",
        "navy",
        "olive",
        "khaki",
        "lavender",
        "lilac",
        "peach",
        "rust",
        "bronze",
        "copper",
        "platinum",
        "emerald",
        "sapphire",
        "ruby",
        "jade",
        "pearl",
        "charcoal",
        "cream",
        "tan",
    ],
    "emotions": [
        "happy",
        "sad",
        "angry",
        "afraid",
        "surprised",
        "disgusted",
        "anxious",
        "nervous",
        "excited",
        "calm",
        "peaceful",
        "lonely",
        "jealous",
        "proud",
        "ashamed",
        "guilty",
        "grateful",
        "hopeful",
        "frustrated",
        "confused",
        "bored",
        "curious",
        "nostalgic",
        "melancholy",
        "furious",
        "terrified",
        "delighted",
        "amused",
        "content",
        "miserable",
        "cheerful",
        "gloomy",
        "ecstatic",
        "euphoric",
        "blissful",
        "serene",
        "tranquil",
        "restless",
        "agitated",
        "irritated",
        "resentful",
        "bitter",
        "envious",
        "compassionate",
        "sympathetic",
        "empathetic",
        "tender",
        "enthusiastic",
        "passionate",
        "indifferent",
        "apathetic",
        "numb",
        "overwhelmed",
        "relieved",
        "skeptical",
        "suspicious",
        "paranoid",
        "vulnerable",
        "insecure",
        "confident",
        "determined",
        "resolute",
        "bewildered",
        "perplexed",
        "astonished",
        "stunned",
        "dumbfounded",
    ],
    "body": [
        "head",
        "face",
        "eye",
        "ear",
        "nose",
        "mouth",
        "tongue",
        "tooth",
        "lip",
        "chin",
        "forehead",
        "neck",
        "shoulder",
        "arm",
        "elbow",
        "wrist",
        "hand",
        "finger",
        "thumb",
        "chest",
        "stomach",
        "back",
        "hip",
        "leg",
        "knee",
        "ankle",
        "foot",
        "toe",
        "skin",
        "bone",
        "muscle",
        "brain",
        "heart",
        "lung",
        "liver",
        "kidney",
        "skull",
        "jaw",
        "cheek",
        "eyebrow",
        "eyelash",
        "nostril",
        "throat",
        "collarbone",
        "ribcage",
        "spine",
        "pelvis",
        "thigh",
        "calf",
        "shin",
        "heel",
        "palm",
        "knuckle",
        "fingernail",
        "tendon",
        "ligament",
        "cartilage",
        "artery",
        "vein",
        "nerve",
        "pancreas",
        "spleen",
        "bladder",
        "intestine",
        "esophagus",
        "colon",
    ],
    "vehicles": [
        "car",
        "truck",
        "bus",
        "van",
        "motorcycle",
        "bicycle",
        "scooter",
        "train",
        "subway",
        "tram",
        "airplane",
        "helicopter",
        "jet",
        "rocket",
        "boat",
        "ship",
        "yacht",
        "canoe",
        "kayak",
        "ferry",
        "ambulance",
        "taxi",
        "limousine",
        "tractor",
        "tank",
        "sedan",
        "convertible",
        "minivan",
        "pickup",
        "jeep",
        "hatchback",
        "trolley",
        "monorail",
        "gondola",
        "catamaran",
        "sailboat",
        "submarine",
        "cruiser",
        "freighter",
        "tanker",
        "barge",
        "glider",
        "biplane",
        "seaplane",
        "hovercraft",
        "segway",
        "rickshaw",
        "chariot",
        "carriage",
        "sleigh",
        "sled",
    ],
    "weather": [
        "rain",
        "snow",
        "wind",
        "storm",
        "thunder",
        "lightning",
        "fog",
        "cloud",
        "sunshine",
        "rainbow",
        "hail",
        "frost",
        "ice",
        "breeze",
        "hurricane",
        "tornado",
        "drought",
        "flood",
        "blizzard",
        "mist",
        "dew",
        "sleet",
        "heat",
        "cold",
        "monsoon",
        "cyclone",
        "typhoon",
        "drizzle",
        "downpour",
        "squall",
        "gust",
        "gale",
        "whirlwind",
        "avalanche",
        "mudslide",
        "tsunami",
        "humidity",
        "overcast",
        "haze",
        "smog",
    ],
    "clothing": [
        "shirt",
        "pants",
        "dress",
        "skirt",
        "jacket",
        "coat",
        "sweater",
        "hoodie",
        "jeans",
        "shorts",
        "suit",
        "tie",
        "scarf",
        "gloves",
        "hat",
        "cap",
        "boots",
        "shoes",
        "sandals",
        "socks",
        "belt",
        "uniform",
        "pajamas",
        "vest",
        "raincoat",
        "blouse",
        "cardigan",
        "tuxedo",
        "gown",
        "robe",
        "kimono",
        "poncho",
        "parka",
        "blazer",
        "overalls",
        "leggings",
        "stockings",
        "apron",
        "bikini",
        "swimsuit",
        "wetsuit",
        "sneakers",
        "heels",
        "loafers",
        "slippers",
        "mittens",
        "earmuffs",
        "beret",
        "turban",
        "tiara",
        "crown",
        "veil",
        "cape",
        "cloak",
        "shawl",
    ],
    "furniture": [
        "chair",
        "table",
        "desk",
        "sofa",
        "couch",
        "bed",
        "mattress",
        "pillow",
        "blanket",
        "shelf",
        "bookcase",
        "cabinet",
        "drawer",
        "wardrobe",
        "mirror",
        "lamp",
        "carpet",
        "curtain",
        "stool",
        "bench",
        "hammock",
        "nightstand",
        "dresser",
        "armoire",
        "ottoman",
        "recliner",
        "futon",
        "crib",
        "bunkbed",
        "headboard",
        "footrest",
        "chandelier",
        "candelabra",
        "vase",
        "rug",
        "tapestry",
        "screen",
        "partition",
        "credenza",
        "hutch",
        "sideboard",
    ],
    "tools": [
        "hammer",
        "screwdriver",
        "wrench",
        "pliers",
        "drill",
        "saw",
        "axe",
        "shovel",
        "rake",
        "scissors",
        "knife",
        "needle",
        "tape",
        "glue",
        "nail",
        "screw",
        "bolt",
        "wire",
        "ladder",
        "rope",
        "chisel",
        "mallet",
        "crowbar",
        "clamp",
        "vise",
        "level",
        "compass",
        "ruler",
        "protractor",
        "caliper",
        "sandpaper",
        "soldering iron",
        "blowtorch",
        "jackhammer",
        "chainsaw",
        "grinder",
        "wheelbarrow",
        "hose",
        "trowel",
        "pickaxe",
        "sickle",
    ],
    "nature": [
        "mountain",
        "river",
        "lake",
        "ocean",
        "sea",
        "forest",
        "jungle",
        "desert",
        "valley",
        "canyon",
        "waterfall",
        "volcano",
        "island",
        "beach",
        "cliff",
        "cave",
        "meadow",
        "prairie",
        "glacier",
        "reef",
        "swamp",
        "marsh",
        "hill",
        "plateau",
        "peninsula",
        "archipelago",
        "lagoon",
        "fjord",
        "delta",
        "estuary",
        "ravine",
        "gorge",
        "ridge",
        "summit",
        "tundra",
        "savanna",
        "steppe",
        "oasis",
        "geyser",
        "spring",
        "brook",
        "creek",
        "pond",
        "bay",
        "cove",
        "strait",
        "cape",
        "dune",
    ],
    "science": [
        "atom",
        "molecule",
        "electron",
        "proton",
        "neutron",
        "photon",
        "gravity",
        "magnetism",
        "electricity",
        "radiation",
        "frequency",
        "wavelength",
        "spectrum",
        "velocity",
        "acceleration",
        "momentum",
        "entropy",
        "energy",
        "mass",
        "force",
        "pressure",
        "temperature",
        "density",
        "viscosity",
        "conductivity",
        "resistance",
        "voltage",
        "cell",
        "gene",
        "DNA",
        "RNA",
        "protein",
        "enzyme",
        "chromosome",
        "nucleus",
        "mitosis",
        "mutation",
        "evolution",
        "species",
        "genome",
        "bacteria",
        "virus",
        "fungus",
        "parasite",
        "antibody",
        "vaccine",
        "microscope",
        "telescope",
        "thermometer",
        "barometer",
        "centrifuge",
        "hypothesis",
        "theory",
        "experiment",
        "observation",
        "equation",
    ],
    "technology": [
        "computer",
        "laptop",
        "tablet",
        "smartphone",
        "keyboard",
        "monitor",
        "printer",
        "scanner",
        "router",
        "modem",
        "server",
        "database",
        "algorithm",
        "software",
        "hardware",
        "processor",
        "memory",
        "storage",
        "internet",
        "website",
        "browser",
        "email",
        "download",
        "upload",
        "pixel",
        "resolution",
        "bandwidth",
        "encryption",
        "firewall",
        "bluetooth",
        "wifi",
        "satellite",
        "antenna",
        "cable",
        "fiber",
        "robot",
        "drone",
        "sensor",
        "microchip",
        "transistor",
        "circuit",
        "battery",
        "solar panel",
        "turbine",
        "generator",
        "laser",
        "hologram",
        "virtual reality",
        "augmented reality",
        "blockchain",
        "artificial intelligence",
        "machine learning",
        "neural network",
    ],
    "architecture": [
        "house",
        "apartment",
        "castle",
        "palace",
        "cathedral",
        "church",
        "mosque",
        "temple",
        "synagogue",
        "monastery",
        "pagoda",
        "shrine",
        "skyscraper",
        "tower",
        "bridge",
        "tunnel",
        "dam",
        "aqueduct",
        "pyramid",
        "colosseum",
        "amphitheater",
        "stadium",
        "arena",
        "lighthouse",
        "windmill",
        "barn",
        "cottage",
        "villa",
        "mansion",
        "bungalow",
        "cabin",
        "igloo",
        "tent",
        "yurt",
        "hut",
        "fortress",
        "citadel",
        "bunker",
        "barracks",
        "garrison",
        "library",
        "museum",
        "gallery",
        "theater",
        "cinema",
        "hospital",
        "school",
        "university",
        "laboratory",
        "observatory",
        "greenhouse",
    ],
}


def build_vocabulary() -> tuple[list[str], list[str]]:
    """Return (words, categories) from the vocabulary dict."""
    words: list[str] = []
    categories: list[str] = []
    for category, word_list in VOCABULARY.items():
        for word in word_list:
            words.append(word)
            categories.append(category)
    print(f"Vocabulary: {len(words)} words across {len(VOCABULARY)} categories")
    return words, categories


def compute_embeddings(words: list[str], model_name: str) -> np.ndarray:
    """Embed words with sentence-transformers."""
    from sentence_transformers import SentenceTransformer

    print(f"Loading model: {model_name}")
    model = SentenceTransformer(model_name)
    print(f"Encoding {len(words)} words...")
    t0 = time.time()
    embeddings = model.encode(words, normalize_embeddings=True, show_progress_bar=False)
    print(f"  Done in {time.time() - t0:.1f}s — shape: {embeddings.shape}")
    return embeddings


def build_tmap(embeddings: np.ndarray, k: int) -> TMAP:
    """Build TMAP with cosine metric."""
    print(f"Fitting TMAP (metric='cosine', k={k})...")
    t0 = time.time()
    model = TMAP(
        metric="cosine",
        n_neighbors=k,
        layout_iterations=1000,
        seed=42,
    ).fit(embeddings.astype(np.float32))
    print(f"  Done in {time.time() - t0:.1f}s")
    return model


def analyze(
    model: TMAP,
    words: list[str],
    categories: list[str],
) -> str:
    """Generate semantic analysis report."""
    tree = model.tree_
    cat_arr = np.array(categories)
    lines: list[str] = []
    w = lines.append

    w(f"Word Embedding TMAP — {len(words)} words, {len(set(categories))} categories\n")

    # 1. Category clustering
    be = boundary_edges(tree, cat_arr)
    w("1. Category boundaries:")
    w(
        f"   Same-category edges: {len(tree.edges) - len(be)} / {len(tree.edges)} "
        f"({1 - len(be) / len(tree.edges):.1%})"
    )
    w(f"   Cross-category edges: {len(be)} ({len(be) / len(tree.edges):.1%})\n")

    # 2. Subtree purity
    purity = subtree_purity(tree, cat_arr, min_size=5)
    valid = purity[~np.isnan(purity)]
    w(f"2. Subtree purity: mean={valid.mean():.3f}  median={np.median(valid):.3f}\n")

    # 3. Most connected category pairs
    cmat, classes = confusion_matrix_from_tree(tree, cat_arr)
    np.fill_diagonal(cmat, 0)
    upper = np.triu_indices_from(cmat, k=1)
    pair_counts = cmat[upper]
    top_idx = np.argsort(pair_counts)[::-1][:10]
    w("3. Most connected category pairs (cross-category tree edges):")
    for i in top_idx:
        if pair_counts[i] == 0:
            break
        r, c = upper[0][i], upper[1][i]
        w(f"   {pair_counts[i]:3d} edges: {classes[r]:>15s}  <->  {classes[c]}")
    w("")

    # 4. Semantic paths — trace between words
    word_to_idx = {w: i for i, w in enumerate(words)}
    paths_to_trace = [
        ("dog", "wolf"),
        ("dog", "cat"),
        ("guitar", "piano"),
        ("salmon", "sushi"),
        ("rain", "snow"),
        ("happy", "sad"),
        ("doctor", "nurse"),
        ("France", "Germany"),
        ("car", "airplane"),
        ("guitar", "violin"),
        ("hammer", "screwdriver"),
        ("mountain", "ocean"),
        ("dog", "guitar"),
        ("happy", "volcano"),
    ]
    w("4. Semantic paths (word → word along the tree):")
    for word_a, word_b in paths_to_trace:
        if word_a not in word_to_idx or word_b not in word_to_idx:
            continue
        idx_a = word_to_idx[word_a]
        idx_b = word_to_idx[word_b]
        path_nodes = tree.path(idx_a, idx_b)
        path_words = [words[n] for n in path_nodes]
        # Show full path if short, otherwise truncated
        if len(path_words) <= 8:
            path_str = " → ".join(path_words)
        else:
            path_str = " → ".join(path_words[:4]) + " → ... → " + " → ".join(path_words[-2:])
        w(f"   {word_a} → {word_b} ({len(path_words)} hops): {path_str}")
    w("")

    return "\n".join(lines)


def create_visualization(
    model: TMAP,
    words: list[str],
    categories: list[str],
) -> TmapViz:
    """Build TmapViz with category coloring and word labels."""

    viz = model.to_tmapviz()
    viz.title = "Word Embeddings — Semantic Map"

    viz.add_color_layout("category", categories, categorical=True, color="tab20")
    viz.add_label("word", words)

    return viz


def main() -> None:
    parser = argparse.ArgumentParser(description="Word embedding TMAP")
    parser.add_argument(
        "--model",
        type=str,
        default="all-MiniLM-L6-v2",
        help="Sentence-transformer model (default: all-MiniLM-L6-v2)",
    )
    parser.add_argument("--k", type=int, default=10, help="Number of neighbors")
    parser.add_argument("--serve", action="store_true")
    parser.add_argument("--port", type=int, default=8050)
    args = parser.parse_args()

    words, categories = build_vocabulary()
    embeddings = compute_embeddings(words, args.model)
    model = build_tmap(embeddings, args.k)

    report = analyze(model, words, categories)
    report_path = OUTPUT_DIR / "word_embeddings_report.txt"
    report_path.write_text(report, encoding="utf-8")
    print(f"\nReport saved to {report_path}")
    print("\n" + report)

    print("Building visualization...")
    viz = create_visualization(model, words, categories)
    html_path = viz.write_html(OUTPUT_DIR / "word_embeddings_tmap")
    print(f"HTML saved to {html_path}")

    if args.serve:
        print(f"Serving on http://127.0.0.1:{args.port}")
        viz.serve(port=args.port)


if __name__ == "__main__":
    main()
